eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
  environment: local
logging:
  level:
    root: DEBUG

server:
  port: 8761